package(default_visibility = ["//src:__pkg__"])

cc_library(
    name = "aarch64",
    srcs = ["aarch64.cc"],
    hdrs = ["platform.hpp"],
)

cc_library(
    name = "x86_64",
    srcs = ["x86_64.cc"],
    hdrs = ["platform.hpp"],
)
