local_repository(
    name = "skip_oss_tensorflow",
    path = "./tensorflow",
)

local_repository(
    name = "skip_experimental",
    path = "./experimental",
)

local_repository(
    name = "ignored_temporary_sources",
    path = "./sources",
)

local_repository(
    name = "ignored_temporary_toolchains",
    path = "./toolchain",
)

local_repository(
    name = "ignored_temporary_docker_build_context",
    path = "./docker_build_context",
)
